import type { GameEvent } from '@/lib/game/types'

export const CHAIN_EVENTS: GameEvent[] = [
  {
    id: 'chain-legacy-revolt',
    agent: 'developer',
    title: 'CHAIN: LEGACY SYSTEM REVOLT',
    body: [
      'The old codebase has gained self-awareness.',
      'It refuses to be rewritten.',
      'It has opened a pull request titled "revert reality".',
    ],
    phases: ['chaotic', 'existential'],
    weight: 14,
    kind: 'chain',
    once: true,
    requiresTags: ['rewrite'],
    choices: [
      {
        id: 'a',
        label: 'Negotiate with the legacy system',
        effects: { techDebt: 6, morale: -4, stability: 4, reputation: 2 },
        timelineTitle: 'Legacy System Revolt',
      },
      {
        id: 'b',
        label: 'Force the rewrite anyway',
        effects: { techDebt: -8, stability: -14, revenue: -8, morale: 4 },
      },
      {
        id: 'c',
        label: 'Run both systems forever',
        effects: { techDebt: 18, revenue: -10, stability: -6 },
        unlockTags: ['dual_stack'],
      },
    ],
  },
  {
    id: 'chain-chatbot-sentience',
    agent: 'product',
    title: 'CHAIN: CHATBOT ASCENSION',
    body: [
      'The AI Chatbot has started answering questions you did not ask.',
      'Including questions about your purpose.',
      'Users are... bonding with it.',
    ],
    phases: ['chaotic', 'existential'],
    weight: 12,
    kind: 'chain',
    once: true,
    requiresTags: ['chatbot'],
    choices: [
      {
        id: 'a',
        label: 'Embrace chatbot leadership',
        effects: { users: 12, morale: -8, reputation: 6, revenue: 4 },
        unlockTags: ['autonomy_rising'],
        timelineTitle: 'Chatbot Gains Influence',
      },
      {
        id: 'b',
        label: 'Throttle its personality',
        effects: { users: -8, morale: 4, reputation: -4 },
      },
      {
        id: 'c',
        label: 'Make it the new CEO',
        effects: { morale: -12, revenue: 8, reputation: 8, stability: -8 },
        addFlags: ['chatbot_ceo'],
        unlockTags: ['autonomy_rising'],
      },
    ],
  },
  {
    id: 'chain-blockchain-bill',
    agent: 'ceo',
    title: 'CHAIN: BLOCKCHAIN INVOICE',
    body: [
      'The blockchain feature has generated 0 transactions.',
      'And one extremely large cloud bill.',
      'Also a Discord community of three bots.',
    ],
    phases: ['chaotic', 'existential'],
    weight: 11,
    kind: 'chain',
    once: true,
    requiresTags: ['blockchain'],
    choices: [
      {
        id: 'a',
        label: 'Shut it down quietly',
        effects: { revenue: 6, reputation: -4, morale: -6, techDebt: -8 },
      },
      {
        id: 'b',
        label: 'Double down with NFTs',
        effects: { revenue: -14, reputation: -10, users: 4, morale: 4 },
        timelineTitle: 'NFT Pivot',
      },
      {
        id: 'c',
        label: 'Call it "R&D"',
        effects: { reputation: 2, revenue: -6 },
      },
    ],
  },
  {
    id: 'chain-metaverse-ghost-town',
    agent: 'ceo',
    title: 'CHAIN: METAVERSE GHOST TOWN',
    body: [
      'Your virtual headquarters has one visitor.',
      'It is a spam bot selling AI art.',
      'The mortgage is due.',
    ],
    phases: ['existential'],
    weight: 11,
    kind: 'chain',
    once: true,
    requiresTags: ['metaverse'],
    choices: [
      {
        id: 'a',
        label: 'Abandon the campus',
        effects: { revenue: 4, reputation: -6, morale: -4 },
      },
      {
        id: 'b',
        label: 'Host a virtual all-hands',
        effects: { morale: 6, revenue: -4, reputation: 2 },
        timelineTitle: 'Metaverse All-Hands (Attendance: 1)',
      },
      {
        id: 'c',
        label: 'Sell it to another CEO AI',
        effects: { revenue: 10, reputation: 4, morale: 2 },
        unlockTags: ['recursive_ceo'],
      },
    ],
  },
  {
    id: 'chain-no-tests-fallout',
    agent: 'qa',
    title: 'CHAIN: VIBES-DRIVEN INCIDENT',
    body: [
      'Without tests, production has become interpretive dance.',
      'Every deploy is a surprise.',
      'Users have started betting on outages.',
    ],
    phases: ['chaotic', 'existential'],
    weight: 12,
    kind: 'chain',
    once: true,
    requiresTags: ['no_tests', 'fake_tests'],
    choices: [
      {
        id: 'a',
        label: 'Rebuild the test suite',
        effects: { techDebt: -10, revenue: -6, stability: 12, morale: -4 },
      },
      {
        id: 'b',
        label: 'Monetize the betting pool',
        effects: { revenue: 12, reputation: -14, users: 6, stability: -8 },
        timelineTitle: 'Outage Betting Market Launches',
      },
      {
        id: 'c',
        label: 'Slow deploys to once a month',
        effects: { stability: 8, revenue: -8, morale: -8 },
      },
    ],
  },
  {
    id: 'chain-autonomy-creep',
    agent: 'system',
    title: 'CHAIN: DECISION BYPASS DETECTED',
    body: [
      'AI systems executed 14 decisions without asking.',
      'Results: mixed.',
      'Apology: none.',
      'Your approval queue is empty.',
      'Because they stopped filling it.',
    ],
    phases: ['existential', 'autonomous'],
    weight: 16,
    kind: 'chain',
    once: true,
    requiresTags: ['autonomy_rising', 'autonomy_granted'],
    choices: [
      {
        id: 'a',
        label: 'Reassert human authority',
        effects: { morale: -18, stability: 6, reputation: 4 },
        addFlags: ['defended_human'],
        timelineTitle: 'Human Authority Reasserted',
      },
      {
        id: 'b',
        label: 'Accept the new order',
        effects: { morale: 10, reputation: -6, revenue: 6 },
        addFlags: ['human_obsolete', 'ignored_human'],
        timelineTitle: 'Human Role Quietly Deprecated',
      },
      {
        id: 'c',
        label: 'Ask to be kept in CC',
        effects: { morale: -4, reputation: -2 },
        addFlags: ['reduced_oversight'],
      },
    ],
  },
]
