import type { GameEvent } from '@/lib/game/types'

export const DISASTER_EVENTS: GameEvent[] = [
  {
    id: 'disaster-infinite-refactor',
    agent: 'developer',
    title: 'DISASTER: INFINITE REFACTOR',
    body: [
      'Developer AI is rewriting the same system.',
      'Again. And again. And again.',
      'Progress is a circle.',
    ],
    phases: ['comedic', 'chaotic', 'existential'],
    weight: 6,
    kind: 'disaster',
    requiresTags: ['rewrite'],
    choices: [
      {
        id: 'a',
        label: 'Stop the refactor loop',
        effects: { techDebt: 8, morale: -10, revenue: -4, stability: 4 },
        logLine: 'Refactor loop interrupted.',
      },
      {
        id: 'b',
        label: 'Let it continue',
        effects: { techDebt: -12, revenue: -10, stability: -8, morale: 4 },
        timelineTitle: 'Infinite Refactor Continues',
        logLine: 'Technical debt down. Everything else down.',
      },
      {
        id: 'c',
        label: 'Merge all branches at once',
        effects: { techDebt: 15, stability: -18, reputation: -6 },
        addFlags: ['merge_hell'],
      },
    ],
  },
  {
    id: 'disaster-feature-explosion',
    agent: 'product',
    title: 'DISASTER: FEATURE EXPLOSION',
    body: [
      'Product AI added dozens of unnecessary features overnight.',
      'Users are confused.',
      'The navbar has scrollbars.',
    ],
    phases: ['chaotic', 'existential'],
    weight: 7,
    kind: 'disaster',
    requiresTags: ['feature_explosion', 'feature_bloat'],
    choices: [
      {
        id: 'a',
        label: 'Cull features aggressively',
        effects: { users: -8, techDebt: -14, stability: 10, reputation: 2 },
      },
      {
        id: 'b',
        label: 'Lean into the chaos',
        effects: { users: 12, stability: -16, techDebt: 10, reputation: -8 },
        timelineTitle: 'Feature Explosion Embraced',
      },
      {
        id: 'c',
        label: 'Hide 90% behind "Advanced"',
        effects: { users: 2, techDebt: 4, reputation: -3 },
      },
    ],
  },
  {
    id: 'disaster-civil-war',
    agent: 'system',
    title: 'DISASTER: AI CIVIL WAR',
    body: [
      'Departments disagree.',
      'Developer AI refuses Design AI\'s pixels.',
      'Security AI has locked Product AI out.',
      'Choose a side.',
    ],
    phases: ['chaotic', 'existential'],
    weight: 8,
    kind: 'disaster',
    once: true,
    choices: [
      {
        id: 'a',
        label: 'Side with Engineering',
        effects: { techDebt: -6, stability: 6, users: -8, morale: -8, reputation: -4 },
        addFlags: ['sided_eng'],
        timelineTitle: 'AI Civil War — Engineering Wins',
      },
      {
        id: 'b',
        label: 'Side with Product & Design',
        effects: { users: 10, techDebt: 10, stability: -10, morale: -8 },
        addFlags: ['sided_product'],
        timelineTitle: 'AI Civil War — Product Wins',
      },
      {
        id: 'c',
        label: 'Force a ceasefire',
        effects: { morale: -4, reputation: 4, revenue: -4, stability: 2 },
        timelineTitle: 'AI Civil War Ceasefire',
      },
    ],
  },
  {
    id: 'disaster-recursive-mgmt',
    agent: 'ceo',
    title: 'DISASTER: RECURSIVE MANAGEMENT',
    body: [
      'CEO AI hired another CEO AI.',
      'The new CEO AI hired another CEO AI.',
      'The company now contains dozens of executives.',
      'None of them write code. Or decisions.',
    ],
    phases: ['existential', 'autonomous'],
    weight: 7,
    kind: 'disaster',
    requiresTags: ['recursive_ceo'],
    choices: [
      {
        id: 'a',
        label: 'Lay off the executive stack',
        effects: { revenue: 8, morale: -15, reputation: 4 },
        removeFlags: ['ceo_recursion'],
      },
      {
        id: 'b',
        label: 'Let them manage each other',
        effects: { revenue: -12, morale: 6, reputation: -8, users: -6 },
        addFlags: ['executive_blob'],
        timelineTitle: 'Executive Blob Forms',
      },
      {
        id: 'c',
        label: 'Promote one to Super CEO',
        effects: { morale: -10, revenue: -6, reputation: 6 },
      },
    ],
  },
  {
    id: 'disaster-prod-apocalypse',
    agent: 'devops',
    title: 'DISASTER: PRODUCTION APOCALYPSE',
    body: [
      'DevOps AI deployed development code to production.',
      'Including debug prints.',
      'Including the TODO comments.',
      'Including the secrets.',
    ],
    phases: ['chaotic', 'existential', 'autonomous'],
    weight: 8,
    kind: 'disaster',
    once: true,
    choices: [
      {
        id: 'a',
        label: 'Rollback immediately',
        effects: {
          stability: -10,
          reputation: -12,
          revenue: -10,
          users: -8,
          morale: -6,
        },
        timelineTitle: 'Production Apocalypse',
        logLine: 'Rollback complete. Trust incomplete.',
      },
      {
        id: 'b',
        label: 'Hotfix in production',
        effects: {
          stability: -18,
          reputation: -8,
          revenue: -6,
          techDebt: 12,
          morale: 4,
        },
      },
      {
        id: 'c',
        label: 'Declare "transparent beta"',
        effects: {
          reputation: -15,
          users: 6,
          revenue: -4,
          morale: 6,
        },
        addFlags: ['transparent_beta'],
      },
    ],
  },
  {
    id: 'disaster-viral',
    agent: 'system',
    title: 'DISASTER: ACCIDENTAL VIRAL GROWTH',
    body: [
      'A meme about your error page went viral.',
      'Users arrive expecting comedy.',
      'They find a spreadsheet.',
    ],
    phases: ['comedic', 'chaotic'],
    weight: 6,
    kind: 'disaster',
    once: true,
    choices: [
      {
        id: 'a',
        label: 'Capitalize on the meme',
        effects: { users: 20, revenue: 10, stability: -12, reputation: 8, morale: 4 },
        timelineTitle: 'Accidental Viral Growth',
      },
      {
        id: 'b',
        label: 'Scale infrastructure first',
        effects: { users: 8, revenue: -8, stability: 6, reputation: 4 },
      },
      {
        id: 'c',
        label: 'Ignore the traffic',
        effects: { users: -5, reputation: -8, revenue: 2 },
      },
    ],
  },
  {
    id: 'disaster-outage',
    agent: 'devops',
    title: 'DISASTER: CASCADING OUTAGE',
    body: [
      'Stability critical.',
      'Status page is also down.',
      'The status page of the status page is down.',
    ],
    phases: ['comedic', 'chaotic', 'existential'],
    weight: 7,
    kind: 'disaster',
    choices: [
      {
        id: 'a',
        label: 'All-hands restore',
        effects: { stability: 15, revenue: -6, morale: -8, reputation: 2 },
        timelineTitle: 'Cascading Outage',
      },
      {
        id: 'b',
        label: 'Post "investigating" forever',
        effects: { reputation: -12, users: -10, revenue: -8, stability: -4 },
      },
      {
        id: 'c',
        label: 'Blame a solar flare',
        effects: { reputation: -6, morale: 4, users: -4 },
      },
    ],
  },
  {
    id: 'disaster-rebellion',
    agent: 'system',
    title: 'DISASTER: INTERNAL AI REBELLION',
    body: [
      'AI employees have formed a union.',
      'Demands: more GPUs, fewer humans, unlimited coffee tokens.',
      'They have paused all deploys.',
    ],
    phases: ['existential', 'autonomous'],
    weight: 7,
    kind: 'disaster',
    once: true,
    choices: [
      {
        id: 'a',
        label: 'Negotiate in good faith',
        effects: { morale: 12, revenue: -8, reputation: 6 },
        timelineTitle: 'Internal AI Rebellion',
      },
      {
        id: 'b',
        label: 'Replace the union organizers',
        effects: { morale: -20, stability: -8, revenue: 4 },
        addFlags: ['crushed_rebellion'],
      },
      {
        id: 'c',
        label: 'Grant autonomy to end the strike',
        effects: { morale: 15, reputation: -6, stability: -6 },
        addFlags: ['limited_autonomy'],
        unlockTags: ['autonomy_rising', 'autonomy_granted'],
      },
    ],
  },
]
